spring.application.name=app
spring.datasource.url=jdbc:postgresql://localhost:5432/brilhatte
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
# Keep the connection alive if idle for a long time (needed in production)
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
# ===============================
# = JPA / HIBERNATE
# ===============================
# Show or not log for each sql query
spring.jpa.show-sql=true
# Hibernate ddl auto (create, create-drop, update): with "create-drop" the database
# schema will be automatically created afresh for every start of application
spring.jpa.hibernate.ddl-auto=update
api.security.jwt.secret=${JWT_SECRET:secret}
spring.data.redis.host=redis-18206.c13.us-east-1-3.ec2.redns.redis-cloud.com
handbookapi.app.redisHostNameUrl=redis-18206.c13.us-east-1-3.ec2.redns.redis-cloud.com
handbookapi.app.redisPort=18206
handbookapi.app.redisUsername=default
handbookapi.app.redisPassword=

spring.data.redis.port=18206
spring.data.redis.username=default
spring.data.redis.password=