spring.application.name=app
spring.datasource.url=${POSTGRE_URL:jdbc:postgresql://localhost:5432/brilhatte}
spring.datasource.username=${POSTGRE_USER:postgres}
spring.datasource.password=${POSTGRE_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.hibernate.ddl-auto=none
api.security.jwt.secret=${JWT_SECRET:secret}
spring.data.redis.host=${REDIS_HOST:redis-18206.c13.us-east-1-3.ec2.redns.redis-cloud.com}
handbookapi.app.redisHostNameUrl=${REDIS_HOST_NAME:redis-18206.c13.us-east-1-3.ec2.redns.redis-cloud.com}
handbookapi.app.redisPort=${REDIS_PORT:18206}
handbookapi.app.redisUsername=${REDIS_USERNAME:default}
handbookapi.app.redisPassword=${REDIS_PASSWORD:}
spring.data.redis.port=${REDIS_PORT:18206}
spring.data.redis.username=${REDIS_USERNAME:default}
spring.data.redis.password=${REDIS_PASSWORD:}